// ═══════════════════════════════════════════════════════════
//  Cell Coding — Cloud deploy manifest (Phase 4 PoC)
//  organ → Kubernetes Deployment YAML 생성
// ═══════════════════════════════════════════════════════════

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { compile } from './compile.js';
import { inspectProgram } from './cell-inspect.js';
import { extractDividePolicies, organHpaSpec } from './cell-divide.js';
import type * as AST from './ast.js';

export interface DeployOptions {
  file: string;
  outDir?: string;
  namespace?: string;
  image?: string;
}

export interface DeployResult {
  ok: boolean;
  file: string;
  outDir: string;
  manifests: string[];
  organs: string[];
  errors: string[];
}

function slug(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function hpaYaml(organName: string, spec: { maxReplicas: number; targetQueueDepth: number }, opts: DeployOptions): string {
  const ns = opts.namespace ?? 'cell-coding';
  const depName = slug(organName);

  return `---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${depName}-hpa
  namespace: ${ns}
  labels:
    cell-coding.io/organ: ${organName}
    app.kubernetes.io/part-of: cell-coding
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${depName}
  minReplicas: 1
  maxReplicas: ${spec.maxReplicas}
  metrics:
    - type: External
      external:
        metric:
          name: cell_signal_queue_depth
          selector:
            matchLabels:
              organ: ${organName}
        target:
          type: AverageValue
          averageValue: "${spec.targetQueueDepth}"
`;
}

function deploymentYaml(
  organName: string,
  cellFile: string,
  opts: DeployOptions,
  program: AST.Program,
): string {
  const ns = opts.namespace ?? 'cell-coding';
  const image = opts.image ?? 'cell-coding/runtime:0.1.0';
  const depName = slug(organName);

  const base = `# Generated by cell deploy · cell deploy 생성
# Organ · 기관: ${organName}
apiVersion: v1
kind: Namespace
metadata:
  name: ${ns}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${depName}-cell
  namespace: ${ns}
  labels:
    cell-coding.io/organ: ${organName}
data:
  program.cell: |
${readFileSync(cellFile, 'utf-8')
  .split('\n')
  .map(line => `    ${line}`)
  .join('\n')}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${depName}
  namespace: ${ns}
  labels:
    cell-coding.io/organ: ${organName}
    app.kubernetes.io/part-of: cell-coding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${depName}
  template:
    metadata:
      labels:
        app: ${depName}
        cell-coding.io/organ: ${organName}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: cell-runtime
          image: ${image}
          env:
            - name: CELL_PROGRAM
              value: /config/program.cell
            - name: CELL_ORGAN
              value: ${organName}
          volumeMounts:
            - name: cell-program
              mountPath: /config
              readOnly: true
      volumes:
        - name: cell-program
          configMap:
            name: ${depName}-cell
---
apiVersion: v1
kind: Service
metadata:
  name: ${depName}
  namespace: ${ns}
  labels:
    cell-coding.io/organ: ${organName}
spec:
  selector:
    app: ${depName}
  ports:
    - name: signals
      port: 8080
      targetPort: 8080
`;

  const dividePolicies = extractDividePolicies(program);
  const hpa = organHpaSpec(dividePolicies, organName);
  if (hpa) {
    return base + hpaYaml(organName, hpa, opts);
  }
  return base;
}

/** Generate Kubernetes manifests per organ · 기관별 K8s manifest 생성 */
export function deployCellFile(opts: DeployOptions): DeployResult {
  const file = resolve(opts.file);
  if (!existsSync(file)) {
    return {
      ok: false,
      file,
      outDir: '',
      manifests: [],
      organs: [],
      errors: [`File not found · 파일 없음: ${file}`],
    };
  }

  let program: AST.Program;
  let diagnostics;
  try {
    ({ program, diagnostics } = compile(readFileSync(file, 'utf-8')));
  } catch (e) {
    return {
      ok: false,
      file,
      outDir: '',
      manifests: [],
      organs: [],
      errors: [e instanceof Error ? e.message : String(e)],
    };
  }

  const errors = diagnostics.filter(d => d.kind === 'error').map(d => d.message);
  if (errors.length) {
    return { ok: false, file, outDir: '', manifests: [], organs: [], errors };
  }

  const inspect = inspectProgram(program, { file, diagnostics });
  const organs = inspect.organs.map(o => o.name);
  if (!organs.length) {
    return {
      ok: false,
      file,
      outDir: '',
      manifests: [],
      organs: [],
      errors: ['No organs found · organ 없음'],
    };
  }

  const outDir = resolve(opts.outDir ?? join(dirname(file), 'deploy', 'k8s'));
  mkdirSync(outDir, { recursive: true });

  const manifests: string[] = [];
  const stem = basename(file, '.cell');

  for (const organ of organs) {
    const yaml = deploymentYaml(organ, file, opts, program);
    const outPath = join(outDir, `${stem}-${slug(organ)}.yaml`);
    writeFileSync(outPath, yaml, 'utf-8');
    manifests.push(outPath);
  }

  const readme = `# Cell Coding deploy · ${stem}

Generated from \`${file.replace(/\\/g, '/')}\`

\`\`\`bash
kubectl apply -f ${outDir.replace(/\\/g, '/')}
\`\`\`

Organs · 기관: ${organs.join(', ')}
`;
  writeFileSync(join(outDir, 'README.md'), readme, 'utf-8');

  return { ok: true, file, outDir, manifests, organs, errors: [] };
}

export function formatDeployHuman(result: DeployResult): string {
  const lines = [
    '',
    '  Cell deploy · 클라우드 배포 (K8s PoC)',
    `  file    : ${result.file.replace(/\\/g, '/').split('/').slice(-2).join('/')}`,
    `  out     : ${result.outDir.replace(/\\/g, '/')}`,
    `  organs  : ${result.organs.join(', ') || '—'}`,
  ];
  if (result.manifests.length) {
    lines.push('', '  Manifests · manifest:');
    for (const m of result.manifests) {
      lines.push(`    ${m.replace(/\\/g, '/').split('/').slice(-1)[0]}`);
    }
    lines.push('', '  Apply · 적용:');
    lines.push(`    kubectl apply -f ${result.outDir.replace(/\\/g, '/')}`);
  }
  if (result.errors.length) {
    lines.push('', '  Errors · 오류:');
    for (const e of result.errors) lines.push(`    ✗ ${e}`);
  }
  lines.push('', result.ok ? '  ✓ deploy OK' : '  ✗ deploy failed');
  return lines.join('\n');
}
