import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from './compile.js';
import {
  transpileProgram,
  transpileCellFile,
  defaultBuildOutPath,
} from './transpiler.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const validator = join(__dirname, '../examples/validator.cell');

describe('transpiler (program-level)', () => {
  it('maps signal field types to TypeScript annotations', () => {
    const src = `
signal Rich {
  name: String;
  count: Number;
  flag: Boolean;
  labelList: List<String>;
  meta: Map<String, Number>;
  maybe: Option<String>;
  combo: String | Number;
}
cell C {
  role: "r";
  membrane { accepts: Rich; emits: Rich; }
  on(Rich x) { emit Rich; }
}`;
    const { program } = compile(src);
    const result = transpileProgram(program);
    assert.equal(result.ok, true);
    assert.match(result.code, /name: string;/);
    assert.match(result.code, /count: number;/);
    assert.match(result.code, /flag: boolean;/);
    assert.match(result.code, /labelList: string\[\];/);
    assert.match(result.code, /meta: Record<string, number>;/);
    assert.match(result.code, /maybe: string \| undefined;/);
    assert.match(result.code, /combo: string \| number;/);
  });

  it('emits standalone preamble when standalone: true', () => {
    const { program } = compile(readMinimalCell());
    const result = transpileProgram(program, { standalone: true });
    assert.equal(result.ok, true);
    assert.match(result.code, /export abstract class BaseCell/);
    assert.doesNotMatch(result.code, /from '\.\.\/transpiled-cell\.js'/);
  });

  it('returns error when cellName is not found', () => {
    const { program } = compile(readMinimalCell());
    const result = transpileProgram(program, { cellName: 'MissingCell' });
    assert.equal(result.ok, false);
    assert.match(result.errors[0], /MissingCell/);
    assert.equal(result.code, '');
  });

  it('includes only signals used by the filtered cell', () => {
    const src = `
signal A { n: Number; }
signal B { n: Number; }
signal C { n: Number; }
cell First {
  role: "a";
  membrane { accepts: A; emits: A; }
  on(A x) { emit A; }
}
cell Second {
  role: "b";
  membrane { accepts: B; emits: B; }
  on(B x) { emit B; }
}`;
    const { program } = compile(src);
    const result = transpileProgram(program, { cellName: 'First' });
    assert.equal(result.ok, true);
    assert.match(result.code, /export interface A/);
    assert.doesNotMatch(result.code, /export interface B/);
    assert.doesNotMatch(result.code, /export interface C/);
    assert.doesNotMatch(result.code, /export class Second/);
  });

  it('defaultBuildOutPath resolves generated/*.ts', () => {
    const out = defaultBuildOutPath('/proj/cells/validator.cell', 'generated');
    assert.match(out.replace(/\\/g, '/'), /generated\/validator\.ts$/);
  });
});

describe('transpiler (file-level)', () => {
  it('transpiles validator.cell with source header', () => {
    const result = transpileCellFile({ file: validator });
    assert.equal(result.ok, true);
    assert.match(result.code, /Generated by Cell Coding transpiler/);
    assert.match(result.code, /Source · 소스:/);
    assert.match(result.code, /validator\.cell/);
  });

  it('returns compile diagnostics as errors', () => {
    const bad = join(__dirname, 'fixtures', 'broken.cell');
    const result = transpileCellFile({ file: bad });
    assert.equal(result.ok, false);
    assert.ok(result.errors.length > 0);
    assert.match(result.errors[0], /^line 1, column 1: Cell 'Broken' must declare/);
  });

  it('returns filesystem error for missing file', () => {
    const result = transpileCellFile({ file: join(__dirname, 'fixtures/no-such-file.cell') });
    assert.equal(result.ok, false);
    assert.ok(result.errors.length > 0);
    assert.equal(result.code, '');
  });
});

/** 최소 cell 소스 (테스트용) */
function readMinimalCell(): string {
  return `
signal S { n: Number; }
cell Tiny {
  role: "minimal";
  membrane { accepts: S; emits: S; }
  on(S x) { emit S; }
}`;
}
